name: amazon_reviews
channels:
  - conda-forge
  - defaults
dependencies:
  # Core Python
  - python=3.9
  
  # Testing
  - pytest>=8.0.0
  - pytest-mock>=3.12.0
  - pytest-cov>=4.1.0
  
  # Data Processing
  - pandas>=2.0.0
  - scikit-learn>=1.0.0
  - tqdm>=4.65.0
  
  # Deep Learning
  - transformers>=4.46.0
  - datasets>=2.14.0
  - accelerate>=0.27.0
  
  # Web Scraping
  - beautifulsoup4>=4.12.0
  - requests>=2.31.0
  
  # Visualization
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  
  # NLP
  - nltk>=3.8.0
  
  # Additional dependencies via pip
  - pip
  - pip:
    - bert-score>=0.3.13
    - peft>=0.7.0
    - trl>=0.7.11
    - huggingface-hub>=0.20.0